# This script configures a multi-container setup to serve MPCAutofill and all
# its dependencies. Simply navigate to the base directory and run
# "docker-compose up" to get started. Optionally, you can pass "-d" to detach
# all containers and their outputs to the background. By default, MPCAutofill
# is served at http://localhost:8000. You can adjust the port near the bottom
# of this file. Many code templates and inspirations are taken from blog post:
# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/

version: "3.4"

services:
  # Unicorn serving Django
  django:
    image: mpcautofill_django
    container_name: mpcautofill_django
    build:
      context: ..
      dockerfile: ./docker/django/Dockerfile
    volumes:
      # Writes to
      - django_static:/MPCAutofill/static
    expose:
      - 8000
    depends_on:
      - postgres
      - elasticsearch

  # Nginx serving Django's static files
  nginx:
    image: mpcautofill_nginx
    container_name: mpcautofill_nginx
    build:
      context: ..
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      # Reads from
      - django_static:/MPCAutofill/static
    ports:
      - "8000:80"
    depends_on:
      - django

  postgres:
    expose:
      - 5432
    ports: []
  elasticsearch:
    network_mode: bridge # this is set to `host` in the parent compose file

# Persistent storage for containers
volumes:
  django_static:
